pipeline{
    agent any
    options { 
        buildDiscarder( logRotator( numToKeepStr: '5') )
        disableConcurrentBuilds()
    }
    stages {
         // run our build
        stage("trigger private build") {
            steps{
                build (
                    job: 'App-Build_traitify-widgets-private',
                    parameters: [
                        string( name: "TRAITIFY_WIDGETS_HASH", value: "${GIT_COMMIT}"),
                        string( name: "TRAITIFY_WIDGETS_BRANCH_NAME", value: "${BRANCH_NAME}")
                    ]
                )
            }
        }
    }
}
