pipeline{
    agent any
    options { 
        buildDiscarder( logRotator( numToKeepStr: '5') )
        disableConcurrentBuilds()
    }
    stages {
         // pull our dependent repos
        stage("get dependencies") {
            steps{
                dir('private') {
                    deleteDir()
                    git ( 
                        url: 'https://github.com/traitify/traitify-widgets-private.git', 
                        credentialsId: '5d46047f-0d3d-4836-9fc5-e370dfc25c09', 
                        branch: '*/master',
                        changelog: false,
                        poll: false
                    )
                }
            }
        }
        // all work is done from the private jenkinsfile
        stage("import private jenkinsfile") {
            steps{
                load 'private/infra/Jenkinsfile'
            }
        }
    }
}