pipeline{
    agent any
    options { 
        buildDiscarder( logRotator( numToKeepStr: '5') )
        disableConcurrentBuilds()
    }
    stages {
         // pull our dependent repos
        stage("get dependencies") {
            steps{
                checkout ( 
                    changelog: false, 
                    poll: false, 
                    scm: [
                        $class: 'GitSCM', 
                        branches: [ [name: '*/master']], 
                        doGenerateSubmoduleConfigurations: false, 
                        extensions: [
                            [ $class: 'CleanBeforeCheckout' ],
                            [ $class: 'RelativeTargetDirectory', relativeTargetDir: 'private']
                        ], 
                        submoduleCfg: [], 
                        userRemoteConfigs: [[
                            credentialsId: '5d46047f-0d3d-4836-9fc5-e370dfc25c09', 
                            url: 'git@github.com:traitify/traitify-widgets-private.git'
                        ]]
                    ]
                )
            }
        }
        // all work is done from the private jenkinsfile
        stage("import private jenkinsfile") {
            steps{
                load 'private/Jenkinsfile'
            }
        }
    }
}